// <auto-generated />
using System;
using EnergiaApi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergiaApi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604224654_AddIndexesDataHora")]
    partial class AddIndexesDataHora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergiaApi.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoRegistrado")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("EnergiaApi.Api.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<double>("LimiteConsumoKwh")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PotenciaWatts")
                        .HasColumnType("float");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            LimiteConsumoKwh = 10.0,
                            Nome = "Ar-condicionado Sala A",
                            PotenciaWatts = 1500.0,
                            Setor = "Administrativo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            LimiteConsumoKwh = 20.0,
                            Nome = "Servidor Datacenter",
                            PotenciaWatts = 800.0,
                            Setor = "TI"
                        });
                });

            modelBuilder.Entity("EnergiaApi.Api.Models.LeituraConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoKwh")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("EquipamentoId", "DataHora");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("EnergiaApi.Api.Models.Alerta", b =>
                {
                    b.HasOne("EnergiaApi.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("EnergiaApi.Api.Models.LeituraConsumo", b =>
                {
                    b.HasOne("EnergiaApi.Api.Models.Equipamento", "Equipamento")
                        .WithMany("Leituras")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("EnergiaApi.Api.Models.Equipamento", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
